services:
  - type: web
    name: coeur
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --worker-class gevent --worker-connections 1000 --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true" 