services:
  - type: web
    name: coeur
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true" 